name: Swift Command Line Tool CI

on:
  push:
    branches:
      - main   # 或者你想要触发 CI 的其他分支
  pull_request:
    branches:
      - main   # 或者你想要触发 CI 的其他分支

jobs:
  list-xcode:
    runs-on: macos-latest
    steps:
      - name: List all installed Xcode versions
        run: |
          ls /Applications | grep Xcode
          xcodebuild -version
  build:
    runs-on: macos-latest

    steps:
    # 1. 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. 设置 Xcode 环境
    # - name: Set up Xcode
    #   uses: macos-actions/setup-xcode@v2
    #   with:
    #     xcode-version: '15.0'  # 或者你需要的具体版本

    # 3. 使用 xcodebuild 编译项目
    - name: Build the project using xcodebuild
      run: |
        xcodebuild -scheme GithubActionTest -sdk macosx -configuration Release clean build -derivedDataPath ./build_output

    # 4. 运行命令行程序
    - name: Run DownloadFile
      run: |
        ./build_output/Build/Products/Release/GithubActionTest https://github.com/Tinuv-Dev/FFMPEGBuilder/releases/download/1.1.4/gmp.zip ./0.mp4

    # 可选: 上传构建产物等
    # - name: Upload build artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: downloadfile-output
    #     path: /path/to/save/output/
